"""empty message

Revision ID: 0677bc5c0689
Revises: 2510f196e394
Create Date: 2021-03-23 01:57:28.240306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0677bc5c0689'
down_revision = '2510f196e394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
