"""empty message

Revision ID: 1880ad1f99ad
Revises: 30fb1b056366
Create Date: 2021-03-19 19:36:13.495765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1880ad1f99ad'
down_revision = '30fb1b056366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vet_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RUN', sa.String(length=12), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.String(length=50), nullable=True),
    sa.Column('is_exotic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veterinary_organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('alias_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('user', sa.Column('vet_user_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'vet_user', ['vet_user_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'vet_user_fk')
    op.drop_table('veterinary_organization')
    op.drop_table('vet_user')
    # ### end Alembic commands ###
