"""empty message

Revision ID: 25df28bd8155
Revises: 53a4827cd093
Create Date: 2021-04-05 17:34:28.498401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25df28bd8155'
down_revision = '53a4827cd093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('user_email', sa.String(), nullable=True))
    op.drop_constraint('pet_pet_user_fk_fkey', 'pet', type_='foreignkey')
    op.create_foreign_key(None, 'pet', 'user', ['user_email'], ['email'])
    op.drop_column('pet', 'pet_user_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('pet_user_fk', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.create_foreign_key('pet_pet_user_fk_fkey', 'pet', 'user', ['pet_user_fk'], ['email'])
    op.drop_column('pet', 'user_email')
    # ### end Alembic commands ###
