"""empty message

Revision ID: 3569bb7526cb
Revises: b26a544d4c78
Create Date: 2021-03-20 04:19:55.454201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3569bb7526cb'
down_revision = 'b26a544d4c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('user_contact_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_contact_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_contact')
    # ### end Alembic commands ###
