"""empty message

Revision ID: 48e71593b656
Revises: ddb3bcf7c50d
Create Date: 2021-03-26 00:58:41.697506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e71593b656'
down_revision = 'ddb3bcf7c50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_vet_user_fk_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'vet_user_fk')
    op.drop_column('user', 'father_family_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('father_family_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('vet_user_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_vet_user_fk_fkey', 'user', 'vet_user', ['vet_user_fk'], ['id'])
    # ### end Alembic commands ###
