"""empty message

Revision ID: 53a4827cd093
Revises: 7cdc6ad06cb1
Create Date: 2021-04-05 16:04:42.932578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a4827cd093'
down_revision = '7cdc6ad06cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('pet', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('nickname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('pet', 'name')
    # ### end Alembic commands ###
