"""empty message

Revision ID: 578b95766c2e
Revises: ee7798fd43f4
Create Date: 2021-03-27 13:42:15.039292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578b95766c2e'
down_revision = 'ee7798fd43f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
