"""empty message

Revision ID: 75e83ec8bd26
Revises: 1880ad1f99ad
Create Date: 2021-03-19 20:06:41.236223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e83ec8bd26'
down_revision = '1880ad1f99ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vet_user', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vet_user', type_='foreignkey')
    op.drop_column('vet_user', 'user_id')
    # ### end Alembic commands ###
