"""empty message

Revision ID: 7e5c3bc4981a
Revises: 8441c1d192b7
Create Date: 2021-03-26 00:52:43.237815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5c3bc4981a'
down_revision = '8441c1d192b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('father_family_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('mother_family_name', sa.String(length=50), nullable=True))
    op.drop_column('user', 'last_name')
    op.add_column('vet_user', sa.Column('father_family_name', sa.String(length=50), nullable=True))
    op.add_column('vet_user', sa.Column('mother_family_name', sa.String(length=50), nullable=True))
    op.drop_column('vet_user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_user', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('vet_user', 'mother_family_name')
    op.drop_column('vet_user', 'father_family_name')
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'mother_family_name')
    op.drop_column('user', 'father_family_name')
    # ### end Alembic commands ###
