"""empty message

Revision ID: b26a544d4c78
Revises: b49f26f81a1b
Create Date: 2021-03-20 04:10:22.539135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26a544d4c78'
down_revision = 'b49f26f81a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_medication', sa.String(length=50), nullable=True),
    sa.Column('pet_exams', sa.String(length=100), nullable=True),
    sa.Column('pet_vaccines', sa.String(length=100), nullable=True),
    sa.Column('pet_controls_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_controls_fk'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vet_user', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'vet_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vet_user', type_='unique')
    op.drop_column('vet_user', 'email')
    op.drop_table('pet_controls')
    # ### end Alembic commands ###
