"""empty message

Revision ID: b9d17f7a8a0b
Revises: 75e83ec8bd26
Create Date: 2021-03-19 20:09:53.138551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d17f7a8a0b'
down_revision = '75e83ec8bd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_user', sa.Column('user_fk', sa.Integer(), nullable=True))
    op.drop_constraint('vet_user_user_id_fkey', 'vet_user', type_='foreignkey')
    op.create_foreign_key(None, 'vet_user', 'user', ['user_fk'], ['id'])
    op.drop_column('vet_user', 'user_id')
    op.add_column('veterinary_organization', sa.Column('vet_user_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'veterinary_organization', 'vet_user', ['vet_user_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'veterinary_organization', type_='foreignkey')
    op.drop_column('veterinary_organization', 'vet_user_fk')
    op.add_column('vet_user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vet_user', type_='foreignkey')
    op.create_foreign_key('vet_user_user_id_fkey', 'vet_user', 'user', ['user_id'], ['id'])
    op.drop_column('vet_user', 'user_fk')
    # ### end Alembic commands ###
