"""empty message

Revision ID: c93a8fff649b
Revises: 48e71593b656
Create Date: 2021-03-26 13:00:06.888566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93a8fff649b'
down_revision = '48e71593b656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('father_family_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('mother_family_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mother_family_name')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'father_family_name')
    # ### end Alembic commands ###
