"""empty message

Revision ID: d13bcba02db0
Revises: 0677bc5c0689
Create Date: 2021-03-24 11:42:02.496110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13bcba02db0'
down_revision = '0677bc5c0689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_vet_user_fk_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'vet_user_fk')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('vet_user_fk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_vet_user_fk_fkey', 'user', 'vet_user', ['vet_user_fk'], ['id'])
    # ### end Alembic commands ###
